"use client"

import { ThemeProvider } from "@/components/theme-provider"
//import type { Metadata } from "next";
import { Inter  } from "next/font/google";

import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import { SessionProvider } from "next-auth/react";
import Footer from "@/components/footer/Footer";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})


export default function RootLayout({
  children ,  params: { session , ...params },

}: Readonly<{
  children: React.ReactNode;
  params:{ session: any}
}>) {
  return (
      <html lang="en" className={inter.className}>
      <body className="w-screen  min-h-screen flex flex-col" > 
      <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <SessionProvider session={session}>
        <Navbar />
        {children}
        <Footer />
          </SessionProvider>
        </ThemeProvider >
        </body>
    </html>
  );
}


/**
 * 
 * export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
 */