"use client"

import { ThemeProvider } from "@/components/theme-provider"
//import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
const inter = Inter({ subsets: ["latin"] });
import { SessionProvider } from "next-auth/react";

export default function RootLayout({
  children ,  params: { session , ...params },

}: Readonly<{
  children: React.ReactNode;
  params:{ session: any}
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SessionProvider session={session}>
        <Navbar />
        {children}
          </SessionProvider>
        </ThemeProvider >
        </body>
    </html>
  );
}


/**
 * 
 * export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
 */